name: icaird-weaklysupervisedlearning
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.2
  - openssl=1.1.1l
  - pip=21.0.1
  - python=3.6.13
  - readline=8.1
  - setuptools=58.0.4
  - sqlite=3.36.0
  - tk=8.6.10
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - cached-property==1.5.2
    - cycler==0.10.0
    - h5py==3.1.0
    - kiwisolver==1.3.1
    - matplotlib==3.3.4
    - numpy==1.19.5
    - opencv-python==4.5.1.48
    - pandas==1.1.5
    - pillow==8.3.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.1
    - scipy==1.5.4
    - six==1.16.0
    - torch==1.3.1
    - torchsummary==1.5.1
    - torchvision==0.4.2
